name: Create Zero Trust SSH connection

on:
  workflow_call:
    inputs:
      zerotrust:
        description: 'Which Zero Trust service to use'
        required: true
        type: string
        default: tailscale # options are tailscale or twingate
      ssh_host:
        description: 'SSH host to set in ssh config'
        required: false
        type: string
        default: ''
      ts_oauth_client_id:
        description: 'Tailscale OAuth client ID'
        required: false
        type: string
        default: ''
      ts_oauth_secret:
        description: 'Tailscale OAuth secret'
        required: false
        type: string
        default: ''
      twingate_service_key:
        description: 'Twingate service key'
        required: false
        type: string
        default: ''
      private_ssh_key:
        description: 'Private SSH key for authentication'
        required: true
        type: string
      known_hosts:
        description: 'Known hosts file content'
        required: false
        type: string
        default: ''

jobs:

  zero-trust-ssh:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Setup Tailscale connection
        if: ${{ inputs.zerotrust == 'tailscale' }}
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ inputs.ts_oauth_client_id }}
          oauth-secret: ${{ inputs.ts_oauth_secret }}
          tags: tag:ci
          use-cache: 'true'

      - name: Setup Twingate connection
        if: ${{ inputs.zerotrust == 'twingate' }}
        uses: twingate/github-action@v1
        with:
          service-key: ${{ inputs.twingate_service_key }}

      - name: Setup SSH key with known hosts
        if: ${{ inputs.known_hosts != '' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ inputs.private_ssh_key }}
          known_hosts: ${{ inputs.known_hosts }}

      - name: Setup SSH key without known hosts
        if: ${{ inputs.known_hosts == '' && inputs.ssh_host != '' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ inputs.private_ssh_key }}
          known_hosts: unnecessary
          if_key_exists: replace
          config: |
            Host ${{ inputs.ssh_host }}
              HostName ${{ inputs.ssh_host }}
              StrictHostKeyChecking no
              ControlMaster auto
              ControlPath ~/.ssh/control-%C
              ControlPersist yes
